version: '3.1'

services:
        mongo:
                image: mongo
                restart: always
                ports: 
                        - '27017:27017'
                environment:
                        MONGO_INITDB_ROOT_USERNAME: root
                        MONGO_INITDB_ROOT_PASSWORD: example

        mongo-express:
                image: mongo-express
                restart: always
                ports:
                        - '18081:8081'
                environment:
                        ME_CONFIG_MONGODB_ADMINUSERNAME: root
                        ME_CONFIG_MONGODB_ADMINPASSWORD: example
                        ME_CONFIG_MONGODB_SERVER: mongo
                depends_on:
                        - mongo
        
        #grafana:
        #        image: grafana/grafana:latest
        #        ports:
        #            - "3000:3000"

        kafka-cluster:
                image: landoop/fast-data-dev
                environment:
                        ADV_HOST: 127.0.0.1
                        RUNTESTS: 0
                ports:
                        - 2181:2181
                        - 3030:3030
                        - 8081-8083:8081-8083
                        - 9581-9585:9581-9585
                        - 9092:9092
                volumes:
                        - ./data:/data/db

        superset:
                image: apache/superset:latest
                container_name: superset
                environment:
                        - ADMIN_USERNAME=admin
                        - ADMIN_EMAIL=admin@superset.com
                        - ADMIN_PASSWORD=admin
                ports:
                        - '8088:8088'

networks:
        mongo-compose-network:
                driver: bridge